### ISSUE TITLE
possibility for car config preview 

### ISSUE THREAD

**Issue by Melti-Rogue** [my-name-is-samael/BeamJoy#18]
in vehicle selector in the beamjoy ui a small popup with a picture for our less car apt players would help out tremedously as it handles the modded vehicles much better that the vanilla ui

**Comment by my-name-is-samael** [comment]
I'll check about the feasibility and UX for this

**Comment by my-name-is-samael** [comment]
The feature will be in the 1.1.0.

Note:
_default.jpg_ images ain't working for these vehicles: etk800, etkc, fullsize, covet, miramar, pessima, md_series, us_semi.
The reason is they are PNG files with JPEG extension, so _libjpg_ cannot open them.
Workaround is to create (temporary) PNG files with the JPEG content
