### ISSUE TITLE
Drift Leaderboard

### ISSUE THREAD

**Issue by KaMiKaZeE1221** [my-name-is-samael/BeamJoy#25]
If possible and easy enough to do, can we have a drift leaderboard just like the races and delivery leaderboards?

**Comment by my-name-is-samael** [comment]
Could you be more specific? Delivery leaderboard only show server top 3 players, and races leaderboard have a record per race.
Would it be for the best drift score, the total session sum, the all time player sum ?
You have to know it is pretty easy to cheat on the drift manager (since it is from the solo game and the mode forced a vehicle). For instance, you take a bus and drive in circle to make your score grow infinitely :/

**Comment by KaMiKaZeE1221** [comment]
😂 I didn't know about the bus situation, my idea would have been to have by the top 3 players total sum, I'm not really sure what your final scope of this project is, but maybe as an alternative we could have drift "races", highest drift scores out of all the participants would obviously be the winner and then have a leaderboard for drift "races" that way?

**Comment by my-name-is-samael** [comment]
I thought about drift races during conception and my points were:
- the basegame doesn't implement drift races
- such gamemode will cause new questions and ask to do choices (how to consider the race is over if someone do not finish and keep accumulating score and prevent players cheating)

I can give you ideas on how to do it but I don't think I will implement it in BeamJoy since it is really specific.

**Comment by KaMiKaZeE1221** [comment]
> I thought about drift races during conception and my points were:
> 
> * the basegame doesn't implement drift races
> * such gamemode will cause new questions and need you to make choices (how to consider the race is over if someone does not finish and keeps accumulating score, preventing players from cheating)
> 
> I can give you ideas on how to do it but I don't think I will implement it in BeamJoy since it is really specific.

Fair enough, I guess there is a fair bit to consider, thanks for your input. 😊
