### ISSUE TITLE
Improve checkpoint radius in race editor

### ISSUE THREAD

**Issue by SaltySnail** [my-name-is-samael/BeamJoy#65]
First of all great work on this mod thus far, I love it.

Right now the default radius is always 1. It would be better if the radius gets inherited from the parent when a new checkpoint is made. Most roads tend to have the same width for extended periods so this would decrease the amount of times you have to press + when creating checkpoints. 

Small example: 
I create the first checkpoint, make the radius 5. 
I then drive to the location I want the second checkpoint in, when I spawn a checkpoint it should also have radius 5.

Also width would be a more fitting name since the checkpoints aren't round.

**Comment by my-name-is-samael** [comment]
Good idea, will be implemented in 1.1.5

**Comment by my-name-is-samael** [comment]
Precisions:

Determined size will be set from previous step:
- if creating waypoints within first step > default size to 1
- else (creating a waypoint in 2nd+ step):
  - if previous step has te same amount of branches (i.g. creating the 2nd branch of 3rd step and 2nd step has 2+ branches) > default to same branch index size from the previous step
  - else (first branch or previous step hasn't much branches) > default to first waypoint size from previous step
  
Labels:
- `Branch 1` will be change to "Checkpoint" if there is no other branch within step
- `Radius` will be change to `Size` if the waypoint is not a stand pit (`Width` is incorrect because the value if half the width)

Others:
- Each parent will have a remove button if there are more than 1 parent
